CursoMOD129/Controllers/AppointmentsController.cs
using Azure.Core;
using CursoMOD129.Data;
using CursoMOD129.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Text;
using static CursoMOD129.CursoMOD129Constants;

namespace CursoMOD129.Controllers
{
    [Authorize(Policy = POLICIES.APP_POLICY_ADMIN.NAME)]
    public class AppointmentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;

        public AppointmentsController(ApplicationDbContext context, IEmailSender emailSender)
        {
            _context = context;
            _emailSender = emailSender;
        }


        public IActionResult Index()
        {
            var appointments = _context
                                    .Appointments
                                    .Include(ap => ap.Medic)
                                    .Include(ap => ap.Client)
                                    .ToList();

            return View(appointments);
        }

        // GET Appointments/Create
        public IActionResult Create() 
        {
            this.SetupAppointments();

            return View();
        }

        // POST Appointments/Create
        [HttpPost]
        public IActionResult Create(Appointment newAppointment)
        {
            if (ModelState.IsValid)
            {
                _context.Appointments.Add(newAppointment);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            this.SetupAppointments();

            return View(newAppointment);
        }


        // GET Appointments/Edit/id
        public IActionResult Edit(int id)
        {
            Appointment? editingAppointment = _context.Appointments.Find(id);

            if (editingAppointment == null) 
            {
                // return NotFound();
                // TODO: Apresentar uma mensagem de erro com um texto explicativo
                return RedirectToAction(nameof(Index));
            }

            this.SetupAppointments();

            return View(editingAppointment);

        }

        // POST Appointment/Edit/id
        [HttpPost]
        public IActionResult Edit(int id, Appointment editingAppointment)
        {
            if (!ModelState.IsValid)
            {
                this.SetupAppointments();
                return View(editingAppointment);
            }
            else
            {
                Appointment? dbAppointment = _context.Appointments
                    .AsNoTracking()
                    .First(ap => ap.ID == id);
                    

                if (dbAppointment == null)
                {
                    // return NotFound();
                    // TODO: Apresentar uma mensagem de erro com um texto explicativo
                    return RedirectToAction(nameof(Index));
                }

                _context.Appointments.Update(editingAppointment);
                _context.SaveChanges();
                // TODO: Apresentar uma mensagem de sucesso
                return RedirectToAction(nameof(Index));
            }
        }



        // GET: Appointments/Delete/id
        public IActionResult Delete(int id)
        {
            Appointment? appointment = _context.Appointments.Find(id);

            if (appointment == null)
            {
                return NotFound();
            }

            SetupAppointments();

            return View(appointment);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            Appointment? deletingAppointment = _context.Appointments.Find(id);

            if (deletingAppointment == null)
            {
                return NotFound();
            }

            _context.Appointments.Remove(deletingAppointment);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }


        // GET: Appointments/MedicAppointmentsHistory/medicID
        public IActionResult MedicAppointmentsHistory(int id)
        {
            TeamMember? medic = _context.TeamMembers.Find(id);
            if (medic == null)
            {
                return NotFound();
            }

            ViewData["MedicName"] = medic.Name;

            var appointmentsHistory = _context.Appointments
                .Include(ap => ap.Client)
                .Where(ap => ap.MedicID == id)
                .Where(ap => ap.Date < DateTime.Now)
                .ToList();

            return View(appointmentsHistory);
        }

        // GET: Appointments/MedicAppointmentsScheduled/medicID
        public IActionResult MedicAppointmentsScheduled(int id)
        {
            TeamMember? medic = _context.TeamMembers.Find(id);
            if (medic == null)
            {
                return NotFound();
            }




            ViewData["MedicName"] = medic.Name;

            var appointmentsScheduled = _context.Appointments
                .Include(ap => ap.Client)
                .Where(ap => ap.MedicID == id)
                .Where(ap => ap.Date >= DateTime.Now)
                .ToList();

            return View("MedicAppointmentsHistory", appointmentsScheduled);
        }


        // GET: Appointments/TodaysAppointments
        public IActionResult TodaysAppointments()
        {
            var todaysAppointments = _context.Appointments
                 .Include(ap => ap.Client)
                 .Include(ap => ap.Medic)
                .Where(ap => ap.Date.Date == DateTime.Now.Date)
                .ToList();

            return View(todaysAppointments);
        }

        // GET: Appointments/TomorrowsAppointments
        public IActionResult TomorrowsAppointments()
        {
            var tomorrowsAppointments = _context.Appointments
                    .Include(ap => ap.Client)
                    .Include(ap => ap.Medic)
                    .Where(ap => ap.Date.Date == DateTime.Today.AddDays(1))
                    .ToList();

            return View(tomorrowsAppointments);
        }

        // GET: Appointments/NextWeeksAppointments
        public IActionResult NextWeeksAppointments()
        {
            var nextweeksAppointments = _context.Appointments
                    .Include(ap => ap.Client)
                    .Include(ap => ap.Medic)
                    .Where(ap => ap.Date.Date >= DateTime.Today.AddDays(1) && ap.Date.Date < DateTime.Today.AddDays(8))
                    .ToList();

            return View(nextweeksAppointments);
        }


        // GET: Appointments/SendEmail
        // id is AppointmentID
        public IActionResult SendEmail(int id)
        {
            Appointment? appointment = _context
                                            .Appointments
                                            .Include(ap => ap.Client)
                                            .Include(ap => ap.Medic)
                                            .First(ap => ap.ID == id);
            
            if (appointment == null)
            {
                return NotFound();
            }


            string clientEmail = appointment.Client.Email;
            string subject = "Do not forget you Today's Appointment";
            string htmlMessage = $"Today, you have an appointment with" +
                          $" Medic: {appointment.Medic.Name} at: {appointment.Time:hh:mm}";

            _emailSender.SendEmailAsync(clientEmail, subject, htmlMessage);

            return RedirectToAction(nameof(TodaysAppointments));
        }

        // GET: Appointments/SendTomorrowsEmails
        public IActionResult SendTomorrowsEmails()
        {
            ICollection<Appointment> tomorrowsAppointments = _context
                                            .Appointments
                                            .Include(ap => ap.Client)
                                            .Include(ap => ap.Medic)
                                            .Where(ap => ap.Date.Date == DateTime.Today.AddDays(1))
                                            .ToList();

            if (tomorrowsAppointments.Count == 0)
            {
                return NotFound();
            }

            string subject = "Do not forget you Tomorrow's Appointment";
            string path = Directory.GetCurrentDirectory();
            string template = System.IO.File.ReadAllText(
                Path.Combine(path, EMAIL.EMAIL_TEMPLATES_FOLDER, EMAIL.TOMORROW_APPOINTMENT_EMAIL_TEMPLATE));

            foreach (Appointment ap in tomorrowsAppointments)
            {
                string clientEmail = ap.Client.Email;
                
                StringBuilder body = new StringBuilder(template);
                body.Replace("#CLIENT_NAME", ap.Client.Name);
                body.Replace("#MEDIC_NAME", ap.Medic.Name);
                body.Replace("#APPOINTMENT_TIME", ap.Time.ToShortTimeString());

                _emailSender.SendEmailAsync(clientEmail, subject, body.ToString());
            }

            return RedirectToAction(nameof(TodaysAppointments));
        }


        // GET: Appointments/SendTomorrowsEmails
        public IActionResult SendNextWeeksEmails()
        {
            ICollection<Appointment> nextWeeksAppointments = _context
                            .Appointments
                            .Include(ap => ap.Client)
                            .Include(ap => ap.Medic)
                            .Where(ap => ap.Date.Date >= DateTime.Today.AddDays(1) && ap.Date.Date < DateTime.Today.AddDays(8))
                            .ToList();

            if (nextWeeksAppointments.Count == 0)
            {
                return NotFound();
            }

            string subject = "Do not forget you Next Week's Appointment";
            string path = Directory.GetCurrentDirectory();

CursoMOD129/Controllers/ClientsController.cs
using CursoMOD129.Data;
using CursoMOD129.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static CursoMOD129.CursoMOD129Constants;

namespace CursoMOD129.Controllers
{
    [Authorize(Policy = POLICIES.APP_POLICY.NAME)]
    public class ClientsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientsController(ApplicationDbContext context)
        {
            _context = context;
        }


        // Get: Clients/[Index]
        public IActionResult Index() 
        {
            var clients = _context.Clients.ToList();

            return View(clients);
        }

        // Get: Clients/Create
        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Client newClient)
        {
            if (ModelState.IsValid) 
            {
                _context.Clients.Add(newClient);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(newClient);
        }

        public IActionResult Edit(int id)
        {
            Client? client = _context.Clients.Find(id);

            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        [HttpPost]
        public IActionResult Edit(Client editingClient)
        {
            if (ModelState.IsValid)
            {
                _context.Clients.Update(editingClient);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(editingClient);
        }

        public IActionResult Delete(int id)
        {
            Client? client = _context.Clients.Find(id);

            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            Client? deletingClient = _context.Clients.Find(id);
            
            if (deletingClient != null)
            {
                _context.Clients.Remove(deletingClient);
                _context.SaveChanges();
            }
            
            return RedirectToAction(nameof(Index));
        }



    }
}

CursoMOD129/Controllers/TeamMembersController.cs
using CursoMOD129.Data;
using CursoMOD129.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using static CursoMOD129.CursoMOD129Constants;

namespace CursoMOD129.Controllers
{
    [Authorize(Policy = POLICIES.APP_POLICY.NAME)]
    public class TeamMembersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IToastNotification _toastNotification;
        private readonly IHtmlLocalizer<Resource> _sharedLocalizer;

        public TeamMembersController(ApplicationDbContext context, IToastNotification toastNotification,
            IHtmlLocalizer<Resource> sharedLocalizer)
        {
            _context = context;
            _toastNotification = toastNotification;
            _sharedLocalizer = sharedLocalizer;
        }


        public IActionResult Index()
        {
            var teamMembers = _context
                .TeamMembers
                .Include(tm => tm.WorkRole)
                .ToList();

            SetupMedicWorkRoleID();

            return View(teamMembers);
        }

        // Get: TeamMembers/Create
        public IActionResult Create()
        {
            SetupTeamMember();

            return View();
        }

        

        [HttpPost]
        public IActionResult Create(TeamMember newTeamMember)
        {
            if (!newTeamMember.IsSpecialtyValid(_context))
            {
                ViewData["IsSpecialtyValidError"] = "Specialty is not valid!";
                _toastNotification.AddErrorToastMessage(_sharedLocalizer["Specialty is not valid!"].Value, 
                    new ToastrOptions { Title = _sharedLocalizer["Team Member Creation Error"].Value });
            }
            else if (ModelState.IsValid)
            {
                _context.TeamMembers.Add(newTeamMember);
                _context.SaveChanges();

                _toastNotification.AddSuccessToastMessage(_sharedLocalizer["Team Member successfully created."].Value,
                    new ToastrOptions { Title = _sharedLocalizer["Team Member Created Successfully"].Value });

                return RedirectToAction(nameof(Index));
            }

            _toastNotification.AddErrorToastMessage(_sharedLocalizer["Please check the form again!"].Value, 
                new ToastrOptions { Title = _sharedLocalizer["Team Member Creation Error"].Value });

            ViewData["WorkRoleID"] = new SelectList(_context.WorkRoles, "ID", "Name");
            return View(newTeamMember);
        }


        // Get: TeamMembers/Edit
        public IActionResult Edit(int id)
        {
            TeamMember? teamMember = _context.TeamMembers.Find(id);

            if (teamMember == null)
            {
                return NotFound();
            }

            SetupTeamMember();

            return View(teamMember);
        }

        [HttpPost]
        public IActionResult Edit(TeamMember editingTeamMember)
        {
            if (!editingTeamMember.IsSpecialtyValid(_context))
            {
                ViewData["IsSpecialtyValidError"] = "Specialty is not valid!";
            }
            else if (ModelState.IsValid) 
            {
                _context.TeamMembers.Update(editingTeamMember);
                _context.SaveChanges();


                string message = string.Format(_sharedLocalizer["Team Member {0} successfully edited."].Value, editingTeamMember.Name);

                _toastNotification.AddSuccessToastMessage(message,
                    new ToastrOptions { Title = _sharedLocalizer["Team Member Edited Successfully"].Value });

                return RedirectToAction(nameof(Index));
            }

            SetupTeamMember();

            return View(editingTeamMember);
        }

        // Get: TeamMembers/Delete/id
        public IActionResult Delete(int id)
        {
            TeamMember? teamMember = _context.TeamMembers.Find(id);

            if (teamMember == null)
            {
                return NotFound();
            }

            SetupTeamMember();

            return View(teamMember);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            TeamMember? deletingTeamMember = _context.TeamMembers.Find(id);

            if (deletingTeamMember != null)
            {
                _context.TeamMembers.Remove(deletingTeamMember);
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }



        private void SetupTeamMember()
        {
            ViewData["WorkRoleID"] = new SelectList(_context.WorkRoles, "ID", "Name");
            SetupMedicWorkRoleID();
        }

        private void SetupMedicWorkRoleID()
        {
            WorkRole medicWorkRole = _context.WorkRoles.First(wr => wr.Name == "Medic"); // SelectList * top(1) from WorkRoles where Name = "Medic"
            ViewData["MedicWorkRoleID"] = medicWorkRole.ID;
        }
    }
}

CursoMOD129/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;

@inject IHtmlLocalizer<Resource> SharedLocalizer


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CursoMOD129</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CursoMOD129.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/mvc-grid/mvc-grid.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CursoMOD129</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TeamMembers" asp-action="Index">@SharedLocalizer["Team Members"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">@SharedLocalizer["Clients"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="Index">@SharedLocalizer["Appointments"]</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    <partial name="_SelectLanguage" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CursoMOD129 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/mvc-grid/mvc-grid.js"></script>

    <script>
        document.querySelectorAll(".mvc-grid").forEach(element => new MvcGrid(element));
    </script>

    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>

CursoMOD129/Views/Shared/_SelectLanguage.cshtml
@using Microsoft.AspNetCore.Localization;
@using Microsoft.Extensions.Options;

@inject IOptions<RequestLocalizationOptions> LocOptions;

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures!
                            .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
                            .ToList();
}

<ul class="navbar-nav select-language">
    <li class="nav-item">
        <div>
            <form id="selectLanguage" asp-controller="Home" asp-action="SetLanguage"
                asp-route-returnUrl="@(Context.Request.Path + Context.Request.QueryString)"
                method="post"
                class="form-horizontal row"
                role="form">
            
            
                <div class="col-md-6 text-end">
                    @SharedLocalizer["Language"]
                </div>

                <div class="col-md-6">
                    <select class="form-control" name="culture" onchange="this.form.submit();"
                            asp-for="@requestCulture!.RequestCulture.UICulture.Name"
                            asp-items="cultureItems">
                    </select>
                </div>
            
            </form>
        </div>

    </li>
</ul>